# render.yaml - Configuration complète pour déployer ton projet Laxer-5
databases:
  # Base de données PostgreSQL
  - name: laxer-5-database
    plan: basic-256mb  # Plan gratuit
    region: oregon
    postgresMajorVersion: "16"
    databaseName: laxer5_db
    user: laxer5_user

services:
  # Service Backend Node.js
  - name: laxer-5-backend
    type: web
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm install
    preDeployCommand: cd server && npm run build  # Lance tes migrations
    startCommand: cd server && npm start
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Configuration email Outlook
      - key: EMAIL_USER
        sync: false  # Ton adresse Outlook
      - key: EMAIL_PASS
        sync: false  # Mot de passe d'application Outlook
      - key: EMAIL_SERVICE
        value: outlook
      - key: EMAIL_DEST
        sync: false  # Adresse où recevoir les messages
      # URL du frontend
      - key: CLIENT_URL
        fromService:
          name: laxer-5-frontend
          type: web
          property: host
      # Variables de base de données
      - key: DATABASE_URL
        fromDatabase:
          name: laxer-5-database
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: laxer-5-database
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        fromDatabase:
          name: laxer-5-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laxer-5-database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: laxer-5-database
          property: database

  # Service Frontend React
  - name: laxer-5-frontend
    type: web
    runtime: static
    region: oregon
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://laxer-5-backend.onrender.com
    # Configuration des routes pour SPA React
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Headers de sécurité
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

# Variables d'environnement partagées
envVarGroups:
  - name: shared-config
    envVars:
      - key: TZ
        value: Europe/Paris
      - key: NODE_ENV
        value: production
      - key: LANG
        value: fr_FR.UTF-8